name: Deployee Dist

# on: [push,workflow_dispatch]  see the alternate below
on:
    - push
    - workflow_dispatch
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4

            - name: Install Nodejs
              uses: actions/setup-node@v4
              with:
                node-version: 17
            - name: checking node version
              run: node -v
            
            #   run: |
            #     echo "Gellow"
            #     echo "${{toJson(github)}}"
            #     github clone https://github.com/${{github.repository}}.git