name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
      - 'README.md'  # Fixed typo from 'READ.md'
      
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Updated from 19 to LTS version
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Verify build output
        run: |
          echo "Build directory contents:"
          ls -la build/ || ls -la dist/ || echo "No build folder found"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            build/
            dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: build-files
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          
      - name: Determine build directory
        id: set-build-dir
        run: |
          if [ -d "build" ]; then
            echo "BUILD_DIR=build" >> $GITHUB_OUTPUT
          elif [ -d "dist" ]; then
            echo "BUILD_DIR=dist" >> $GITHUB_OUTPUT
          else
            echo "ERROR: No build directory found" && exit 1
          fi
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment